TURSO_DATABASE_URL = "libsql://privatezomato-mahantesh-pattadkal-1993.aws-ap-south-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjU4NjY4NDgsImlkIjoiODQzYjBlMzItN2FhMS00NzcwLTkwODctODRlOWNlZmExYTM5IiwicmlkIjoiZWNiZjI3MmUtNGJhYS00YzVkLWIwYTYtMGY2ZDk5YjNhOTk1In0.9CSsYH9LwxjnuDlZNRLlcfPB3mqaHAInxhL0EsKoJ7QzCgwZONd4x8O6sUr-mjBKqUlUCnzmNzB5ZsFIEUfzAg" 


POSTGRES_HOST = "private-zomato-mpattadkal-e565.l.aivencloud.com"
POSTGRES_PORT = 23459
POSTGRES_DB = "defaultdb"
POSTGRES_USER = "avnadmin"
POSTGRES_PASSWORD = "AVNS_dQHnEa5bvIc_ReNoy5a"